USE yacedb;
/*
	rajout de AUTO_INCREMENT
*/
ALTER TABLE `yattribute` MODIFY COLUMN `idYATTRIBUTE` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `yattributevalue` MODIFY COLUMN `idYATTRIBUTEVALUE` int(11) NOT NULL AUTO_INCREMENT;